server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: cn-beijing
    keyId: 改成自己的
    keySecret: 改成自己的
    bucketName: 改成自己的


